### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by timmac-qmc** [SuperJMN/DotNet-Ssh-Deployer#5]
Hi,

I've got a fork with some additional features, mainly support for running post deployment commands (including use of sudo).
If this repo is still active I'll submit a PR otherwise I'll make a "DotNet-Ssh-Deployer-Plus" version and manage separately.

Let me know otherwise I'll assume it's no longer maintained.

**Comment by SuperJMN** [comment]
Hey hey! Not currently developing this, but I'm glad someone uses it. Feel free to post your PR. 
Thanks for your interest!

**Comment by timmac-qmc** [comment]
No problem, if you could create an updated nuget package that would be great.

**Comment by SuperJMN** [comment]
Done! From now on, every change in master will generate a new package automatically.
I've also fixed the package Id. The new packages are located here:

https://www.nuget.org/packages/DotNetSsh
https://www.nuget.org/packages/DotNetSsh.App

**Comment by timmac-qmc** [comment]
Nice, to clarify install command is now:

dotnet tool install --global DotNetSsh.App --version 3.2.0
